---
- name: Install Openvpn
  become: true
  package:
    name: "{{ item }}"
  with_items: "{{ openvpn_packages }}"

- name: Create OpenVPN config file
  become: true
  template:
    src: "{{ openvpn_custom_template | default('client.conf.j2') }}"
    dest: "/etc/openvpn/{{ openvpn_name }}.conf"
    mode: 0640
  notify: restart openvpn

- name: Enable OpenVPN autostart.
  become: true
  lineinfile:
    path: /etc/default/openvpn
    regexp: '^AUTOSTART='
    line: 'AUTOSTART="{{ openvpn_name }}"'
  notify: restart openvpn
  when: ansible_os_family == 'Debian'

- name: Enable OpenVPN autostart.
  become: true
  systemd:
    name: "openvpn@{{ openvpn_name }}"
    state: started
    enabled: yes
  when: ansible_os_family == 'RedHat'

- name: start openvpn
  become: true
  service:
    name: openvpn
    state: started
    enabled: true
