---
# tasks file for arillso.openvpn

- name: install openvpn
  become: true
  package:
    name: "{{ item }}"
  with_items: "{{ openvpn_packages }}"
  tags:
    - packages

- name: Create OpenVPN config file
  become: true
  template:
    src: client.conf.j2
    dest: "/etc/openvpn/{{ openvpn_name }}.conf"
    mode: 0640
  notify: restart openvpn
  tags:
    - configuration

- name: Enable OpenVPN autostart.
  become: true
  lineinfile:
    path: /etc/default/openvpn
    regexp: '^AUTOSTART='
    line: 'AUTOSTART="{{ openvpn_name }}"'
  notify: restart openvpn
  tags:
    - configuration
